apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiRGF2aWRKb2hhbm5lc1MiLCJwYXNzd29yZCI6ImdocF9uZlpsRVBUbk41dnI4cUhvWEpobWRBSkwwWFNSTWUyb3FaN1kiLCJlbWFpbCI6ImRhdmlkam9oYW5uZXNTREBnbWFpbC5jb20iLCJhdXRoIjoiUkdGMmFXUktiMmhoYm01bGMxTTZaMmh3WDI1bVdteEZVRlJ1VGpWMmNqaHhTRzlZU21odFpFRktUREJZVTFKTlpUSnZjVm8zV1E9PSJ9fX0=
kind: Secret
metadata:
  name: ghcr-creds
  namespace: paperless
type: kubernetes.io/dockerconfigjson
