apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-backend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: backend.local.meow
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless-backend
                port:
                  number: 8083
