apiVersion: v1
kind: Service
metadata:
  name: paperless-backend
  labels:
    app: paperless-backend
spec:
  selector:
    app: paperless-backend
  ports:
    - name: http
      port: 8083
      targetPort: 8083
